### ISSUE TITLE
Problem with interstitial ads in version 0.6.0. The ad starts. I close it. But it remains as a separate application in multitask.

### ISSUE THREAD

**Issue by semencher** [vtr0n/react-native-yandex-mobile-ads#16]

**Comment by vtr0n** [comment]
Most likely, this happened due to changes in the SDK of the latest version.
SDK has banned advertising outside of the main thread (which react-native does by default). 
I made a wrapper so that the ads run in the main thread.

Perhaps a similar wrapper should be added [here](https://github.com/vtr0n/react-native-yandex-mobile-ads/blob/main/android/src/main/java/com/reactnativeyandexmobileads/InterstitialAdManager.java#L64)

**Comment by semencher** [comment]
Спасибо за быстрый ответ! Но я не понял какую именно обертку я должен написать? Не планируете ли вы написать патч этой баги? Очень надо.)
